/**
 * Meta build data loader.
 *
 * Loads per-queue JSON files produced by `scripts/fetch-meta-builds.ts` and
 * exposes a typed interface for the coaching prompt builder.
 *
 * The JSON files are keyed by champion numeric ID (Champion.key), which is
 * the same key used by the Riot Match-v5 API. Champion name lookups are done
 * via the existing game data champion map.
 */

// Vite resolves these imports at build time. If a file is missing (e.g. data
// hasn't been collected yet), the import will fail — so we use optional
// dynamic loading to handle the empty state gracefully.

export interface MetaBuildRunes {
  statPerks: {
    defense: number;
    flex: number;
    offense: number;
  };
  styles: Array<{
    description: string;
    style: number;
    selections: Array<{
      perk: number;
      var1: number;
      var2: number;
      var3: number;
    }>;
  }>;
}

export interface MetaBuild {
  items: number[];
  perks: MetaBuildRunes;
  winRate: number;
  pickRate: number;
  games: number;
}

export interface MetaBuildAugment {
  augmentId: number;
  picks: number;
  wins: number;
  pickRate: number;
  winRate: number;
}

export interface MetaBuildSpell {
  /** Normalized (ascending) summoner-spell ID pair, e.g. [4, 6] for Flash + Ghost. */
  spells: number[];
  picks: number;
  wins: number;
  pickRate: number;
  winRate: number;
}

export interface MetaBuildItemPoolEntry {
  /** DDragon item id. */
  itemId: number;
  /** Fraction of the champion's selected games that built this item (0..1). */
  presence: number;
}

export interface MetaBuildChampion {
  championName: string;
  sampleSize: number;
  builds: MetaBuild[];
  /**
   * Presence-sourced item pool, ranked by presence descending. Present in files
   * produced by the current pipeline (ARAM); absent in legacy ranked-solo/arena
   * files that predate it, where the pool is derived from `builds` instead.
   */
  itemPool?: MetaBuildItemPoolEntry[];
  popularAugments?: MetaBuildAugment[];
  popularSpells?: MetaBuildSpell[];
}

export interface MetaBuildFile {
  patch: string;
  region: string;
  queueId: number;
  queueName: string;
  collectedAt: string;
  /** Champion numeric ID → builds for that champion */
  champions: Record<string, MetaBuildChampion>;
}

/**
 * Meta build data indexed by the queue the data was collected for.
 * Each key maps to a file's contents, or null if the file doesn't exist yet.
 */
export interface MetaBuildIndex {
  aram: MetaBuildFile | null;
  rankedSolo: MetaBuildFile | null;
  arena: MetaBuildFile | null;
}

/** Module map shape produced by Vite's lazy `import.meta.glob`. */
type GlobModules = Record<string, () => Promise<unknown>>;

/**
 * Acquire the meta-build module map via Vite's `import.meta.glob`.
 *
 * `import.meta.glob` is a Vite build-time transform: Vite (and Vitest) rewrite
 * the CALL below into a static map of lazy importers. Under tsx/Node (the
 * offline harnesses like audit-augments / dump-data) there is no transform, so
 * the call throws "import.meta.glob is not a function"; we catch that and
 * return null so the loader degrades to a "not collected yet" index.
 *
 * Do NOT guard with `typeof import.meta.glob` instead: Vite only rewrites the
 * call expression, so the bare reference is undefined in the bundled renderer
 * too. That form silently strips meta builds from production coaching prompts
 * while still working under tsx, which is exactly the regression this replaces.
 */
function acquireGlobModules(): GlobModules | null {
  try {
    // The `eager: false` default (async loaders) means each file is only
    // fetched/parsed when actually requested, keeping startup fast.
    return import.meta.glob("../../data/meta-builds/*.json");
  } catch {
    return null;
  }
}

/**
 * Load meta build data from the per-queue JSON files in
 * `src/data/meta-builds/`. Files live under `src/` so Vite bundles them into
 * the app; they are generated by `scripts/fetch-meta-builds.ts` and checked
 * into the repo. A missing or unreadable file returns null for that queue, and
 * the prompt builder handles the "not collected yet" case gracefully.
 *
 * `modulesOverride` is a test seam: production passes nothing and the Vite glob
 * map is used; tests inject a fake map to exercise the load and degrade paths
 * deterministically (Vitest's own glob can't reproduce the renderer's
 * absent-reference behavior).
 */
export async function loadMetaBuilds(
  modulesOverride?: GlobModules | null
): Promise<MetaBuildIndex> {
  // `undefined` means "not provided, use the Vite glob"; `null` means "no map
  // available" and drops straight to the degrade path. Distinguishing them (vs
  // `??`) lets a test exercise the null fallback that mirrors the tsx harnesses,
  // where `acquireGlobModules` itself returns null.
  const modules =
    modulesOverride === undefined ? acquireGlobModules() : modulesOverride;
  if (!modules) {
    return { aram: null, rankedSolo: null, arena: null };
  }

  const loadFile = async (name: string): Promise<MetaBuildFile | null> => {
    // Match against the relative path ending with /{name}.json
    const entry = Object.entries(modules).find(([path]) =>
      path.endsWith(`/${name}.json`)
    );
    if (!entry) return null;
    try {
      const mod = (await entry[1]()) as { default: MetaBuildFile };
      return mod.default;
    } catch {
      return null;
    }
  };

  const [aram, rankedSolo, arena] = await Promise.all([
    loadFile("aram"),
    loadFile("ranked-solo"),
    loadFile("arena"),
  ]);

  return { aram, rankedSolo, arena };
}

/**
 * Look up meta builds for a specific champion in a specific meta file.
 * Returns null if the file is missing, the champion isn't in the data, or
 * has no builds above the minimum cluster threshold.
 */
export function getChampionMeta(
  file: MetaBuildFile | null,
  championKey: number
): MetaBuildChampion | null {
  if (!file) return null;
  return file.champions[String(championKey)] ?? null;
}

/**
 * One item in a champion's derived pool for the coaching prompt: the item id and
 * its presence rate (fraction of the champion's games that built it), or null
 * when the source is a legacy build-cluster file that predates presence
 * tracking. Consumers show the rate when present and omit it otherwise.
 */
export interface DerivedPoolItem {
  itemId: number;
  presence: number | null;
}

/**
 * Derive a champion's item pool as ordered entries for the coaching prompt.
 *
 * Prefers the presence-sourced `itemPool` (already ranked by presence
 * descending), carrying each item's presence rate through. Falls back to the
 * legacy exact-set `builds` for ranked-solo/arena files that predate item-pool
 * tracking, ordering those by how many build clusters each item appears in
 * (most common first) and reporting a null rate since clusters carry no true
 * presence. Returns an empty array when neither source has data.
 */
export function deriveMetaItemPoolEntries(
  champion: MetaBuildChampion | null
): DerivedPoolItem[] {
  if (!champion) return [];

  // Preferred source: the presence-sourced pool, already ranked by presence
  // descending. Carry the rate through so the prompt can show how-standard each
  // item is (e.g. a 62% core vs a 28% situational pickup).
  if (champion.itemPool && champion.itemPool.length > 0) {
    return champion.itemPool.map((e) => ({
      itemId: e.itemId,
      presence: e.presence,
    }));
  }

  // Legacy fallback: ranked-solo/arena files predate the pool and still carry
  // exact-set build clusters. Rank items by how many clusters they appear in
  // (most common first); clusters carry no true presence rate, so report null.
  if (champion.builds.length === 0) return [];
  const itemCounts = new Map<number, number>();
  for (const build of champion.builds) {
    for (const itemId of build.items) {
      itemCounts.set(itemId, (itemCounts.get(itemId) ?? 0) + 1);
    }
  }
  return [...itemCounts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0] - b[0])
    .map(([itemId]) => ({ itemId, presence: null }));
}

/**
 * The set of unique item IDs in a champion's pool, ordered most-relevant first.
 * Thin wrapper over deriveMetaItemPoolEntries for callers that only need ids
 * (e.g. tier-1 lookup and tier-2 exclusion); see that function for the
 * source-selection rules.
 */
export function deriveMetaItemPool(
  champion: MetaBuildChampion | null
): number[] {
  return deriveMetaItemPoolEntries(champion).map((e) => e.itemId);
}

/**
 * The single summoner-spell pair to recommend for a champion: the most-picked
 * pair (`popularSpells` is already ranked by pick popularity). Returns undefined
 * when the data isn't collected, the champion has no pairs, or the top pair is
 * incomplete, so callers can omit the recommendation rather than render half of
 * one. Recommendation is by popularity, never win rate.
 */
export function deriveRecommendedSpells(
  champion: MetaBuildChampion | null
): [number, number] | undefined {
  const pair = champion?.popularSpells?.[0]?.spells;
  return pair && pair.length === 2 ? [pair[0], pair[1]] : undefined;
}
