/**
 * Meta build data loader.
 *
 * Loads per-queue JSON files produced by `scripts/fetch-meta-builds.ts` and
 * exposes a typed interface for the coaching prompt builder.
 *
 * The JSON files are keyed by champion numeric ID (Champion.key), which is
 * the same key used by the Riot Match-v5 API. Champion name lookups are done
 * via the existing game data champion map.
 */

// Vite resolves these imports at build time. If a file is missing (e.g. data
// hasn't been collected yet), the import will fail — so we use optional
// dynamic loading to handle the empty state gracefully.

export interface MetaBuildRunes {
  statPerks: {
    defense: number;
    flex: number;
    offense: number;
  };
  styles: Array<{
    description: string;
    style: number;
    selections: Array<{
      perk: number;
      var1: number;
      var2: number;
      var3: number;
    }>;
  }>;
}

export interface MetaBuild {
  items: number[];
  perks: MetaBuildRunes;
  winRate: number;
  pickRate: number;
  games: number;
}

export interface MetaBuildAugment {
  augmentId: number;
  picks: number;
  wins: number;
  pickRate: number;
  winRate: number;
}

export interface MetaBuildSpell {
  /** Normalized (ascending) summoner-spell ID pair, e.g. [4, 6] for Flash + Ghost. */
  spells: number[];
  picks: number;
  wins: number;
  pickRate: number;
  winRate: number;
}

export interface MetaBuildChampion {
  championName: string;
  sampleSize: number;
  builds: MetaBuild[];
  popularAugments?: MetaBuildAugment[];
  popularSpells?: MetaBuildSpell[];
}

export interface MetaBuildFile {
  patch: string;
  region: string;
  queueId: number;
  queueName: string;
  collectedAt: string;
  /** Champion numeric ID → builds for that champion */
  champions: Record<string, MetaBuildChampion>;
}

/**
 * Meta build data indexed by the queue the data was collected for.
 * Each key maps to a file's contents, or null if the file doesn't exist yet.
 */
export interface MetaBuildIndex {
  aram: MetaBuildFile | null;
  rankedSolo: MetaBuildFile | null;
  arena: MetaBuildFile | null;
}

/** Module map shape produced by Vite's lazy `import.meta.glob`. */
type GlobModules = Record<string, () => Promise<unknown>>;

/**
 * Acquire the meta-build module map via Vite's `import.meta.glob`.
 *
 * `import.meta.glob` is a Vite build-time transform: Vite (and Vitest) rewrite
 * the CALL below into a static map of lazy importers. Under tsx/Node (the
 * offline harnesses like audit-augments / dump-data) there is no transform, so
 * the call throws "import.meta.glob is not a function"; we catch that and
 * return null so the loader degrades to a "not collected yet" index.
 *
 * Do NOT guard with `typeof import.meta.glob` instead: Vite only rewrites the
 * call expression, so the bare reference is undefined in the bundled renderer
 * too. That form silently strips meta builds from production coaching prompts
 * while still working under tsx, which is exactly the regression this replaces.
 */
function acquireGlobModules(): GlobModules | null {
  try {
    // The `eager: false` default (async loaders) means each file is only
    // fetched/parsed when actually requested, keeping startup fast.
    return import.meta.glob("../../data/meta-builds/*.json");
  } catch {
    return null;
  }
}

/**
 * Load meta build data from the per-queue JSON files in
 * `src/data/meta-builds/`. Files live under `src/` so Vite bundles them into
 * the app; they are generated by `scripts/fetch-meta-builds.ts` and checked
 * into the repo. A missing or unreadable file returns null for that queue, and
 * the prompt builder handles the "not collected yet" case gracefully.
 *
 * `modulesOverride` is a test seam: production passes nothing and the Vite glob
 * map is used; tests inject a fake map to exercise the load and degrade paths
 * deterministically (Vitest's own glob can't reproduce the renderer's
 * absent-reference behavior).
 */
export async function loadMetaBuilds(
  modulesOverride?: GlobModules | null
): Promise<MetaBuildIndex> {
  // `undefined` means "not provided, use the Vite glob"; `null` means "no map
  // available" and drops straight to the degrade path. Distinguishing them (vs
  // `??`) lets a test exercise the null fallback that mirrors the tsx harnesses,
  // where `acquireGlobModules` itself returns null.
  const modules =
    modulesOverride === undefined ? acquireGlobModules() : modulesOverride;
  if (!modules) {
    return { aram: null, rankedSolo: null, arena: null };
  }

  const loadFile = async (name: string): Promise<MetaBuildFile | null> => {
    // Match against the relative path ending with /{name}.json
    const entry = Object.entries(modules).find(([path]) =>
      path.endsWith(`/${name}.json`)
    );
    if (!entry) return null;
    try {
      const mod = (await entry[1]()) as { default: MetaBuildFile };
      return mod.default;
    } catch {
      return null;
    }
  };

  const [aram, rankedSolo, arena] = await Promise.all([
    loadFile("aram"),
    loadFile("ranked-solo"),
    loadFile("arena"),
  ]);

  return { aram, rankedSolo, arena };
}

/**
 * Look up meta builds for a specific champion in a specific meta file.
 * Returns null if the file is missing, the champion isn't in the data, or
 * has no builds above the minimum cluster threshold.
 */
export function getChampionMeta(
  file: MetaBuildFile | null,
  championKey: number
): MetaBuildChampion | null {
  if (!file) return null;
  return file.champions[String(championKey)] ?? null;
}

/**
 * Derive the set of unique item IDs that appear in the top builds for a
 * champion — the "meta-derived item pool" used as Tier 1 in the coaching
 * prompt. Returns IDs sorted by frequency across the builds (most common
 * first), so the prompt can prioritize items that show up in multiple builds.
 */
export function deriveMetaItemPool(
  champion: MetaBuildChampion | null
): number[] {
  if (!champion || champion.builds.length === 0) return [];

  // Count how many builds each item appears in
  const itemCounts = new Map<number, number>();
  for (const build of champion.builds) {
    for (const itemId of build.items) {
      itemCounts.set(itemId, (itemCounts.get(itemId) ?? 0) + 1);
    }
  }

  // Sort by frequency desc, then by item ID for stable ordering
  return [...itemCounts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0] - b[0])
    .map(([itemId]) => itemId);
}

/**
 * The single summoner-spell pair to recommend for a champion: the most-picked
 * pair (`popularSpells` is already ranked by pick popularity). Returns undefined
 * when the data isn't collected, the champion has no pairs, or the top pair is
 * incomplete, so callers can omit the recommendation rather than render half of
 * one. Recommendation is by popularity, never win rate.
 */
export function deriveRecommendedSpells(
  champion: MetaBuildChampion | null
): [number, number] | undefined {
  const pair = champion?.popularSpells?.[0]?.spells;
  return pair && pair.length === 2 ? [pair[0], pair[1]] : undefined;
}
