/**
 * Meta build data loader.
 *
 * Loads per-queue JSON files produced by `scripts/fetch-meta-builds.ts` and
 * exposes a typed interface for the coaching prompt builder.
 *
 * The JSON files are keyed by champion numeric ID (Champion.key), which is
 * the same key used by the Riot Match-v5 API. Champion name lookups are done
 * via the existing game data champion map.
 */

// Vite resolves these imports at build time. If a file is missing (e.g. data
// hasn't been collected yet), the import will fail — so we use optional
// dynamic loading to handle the empty state gracefully.

export interface MetaBuildRunes {
  statPerks: {
    defense: number;
    flex: number;
    offense: number;
  };
  styles: Array<{
    description: string;
    style: number;
    selections: Array<{
      perk: number;
      var1: number;
      var2: number;
      var3: number;
    }>;
  }>;
}

export interface MetaBuild {
  items: number[];
  perks: MetaBuildRunes;
  winRate: number;
  pickRate: number;
  games: number;
}

export interface MetaBuildAugment {
  augmentId: number;
  picks: number;
  wins: number;
  pickRate: number;
  winRate: number;
}

export interface MetaBuildChampion {
  championName: string;
  sampleSize: number;
  builds: MetaBuild[];
  popularAugments?: MetaBuildAugment[];
}

export interface MetaBuildFile {
  patch: string;
  region: string;
  queueId: number;
  queueName: string;
  collectedAt: string;
  /** Champion numeric ID → builds for that champion */
  champions: Record<string, MetaBuildChampion>;
}

/**
 * Meta build data indexed by the queue the data was collected for.
 * Each key maps to a file's contents, or null if the file doesn't exist yet.
 */
export interface MetaBuildIndex {
  aram: MetaBuildFile | null;
  rankedSolo: MetaBuildFile | null;
  arena: MetaBuildFile | null;
}

/**
 * Load meta build data from the JSON files in `src/data/meta-builds/`.
 *
 * Uses Vite's glob import to dynamically include whatever files exist. Missing
 * files return null for that queue — the prompt builder gracefully handles
 * the case where meta data isn't available yet.
 *
 * Files live under `src/` so Vite bundles them into the app. They are
 * generated by `scripts/fetch-meta-builds.ts` and checked into the repo.
 */
export async function loadMetaBuilds(): Promise<MetaBuildIndex> {
  // Vite glob import resolves at build time. The `eager: false` default
  // (async loaders) means each file is only fetched/parsed when actually
  // requested, keeping startup fast.
  const modules = import.meta.glob("../../data/meta-builds/*.json");

  const loadFile = async (name: string): Promise<MetaBuildFile | null> => {
    // Match against the relative path ending with /{name}.json
    const entry = Object.entries(modules).find(([path]) =>
      path.endsWith(`/${name}.json`)
    );
    if (!entry) return null;
    try {
      const mod = (await entry[1]()) as { default: MetaBuildFile };
      return mod.default;
    } catch {
      return null;
    }
  };

  const [aram, rankedSolo, arena] = await Promise.all([
    loadFile("aram"),
    loadFile("ranked-solo"),
    loadFile("arena"),
  ]);

  return { aram, rankedSolo, arena };
}

/**
 * Look up meta builds for a specific champion in a specific meta file.
 * Returns null if the file is missing, the champion isn't in the data, or
 * has no builds above the minimum cluster threshold.
 */
export function getChampionMeta(
  file: MetaBuildFile | null,
  championKey: number
): MetaBuildChampion | null {
  if (!file) return null;
  return file.champions[String(championKey)] ?? null;
}

/**
 * Derive the set of unique item IDs that appear in the top builds for a
 * champion — the "meta-derived item pool" used as Tier 1 in the coaching
 * prompt. Returns IDs sorted by frequency across the builds (most common
 * first), so the prompt can prioritize items that show up in multiple builds.
 */
export function deriveMetaItemPool(
  champion: MetaBuildChampion | null
): number[] {
  if (!champion || champion.builds.length === 0) return [];

  // Count how many builds each item appears in
  const itemCounts = new Map<number, number>();
  for (const build of champion.builds) {
    for (const itemId of build.items) {
      itemCounts.set(itemId, (itemCounts.get(itemId) ?? 0) + 1);
    }
  }

  // Sort by frequency desc, then by item ID for stable ordering
  return [...itemCounts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0] - b[0])
    .map(([itemId]) => itemId);
}
